name: build-android

on: [push, pull_request]

jobs:
  build:
    runs-on:  ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Configure
      run: ./android-configure $ANDROID_SDK_ROOT/ndk-bundle arm64 23

    - name: Make
      run: LDFLAGS=-shared make -j4
